# Generated by Django 4.0.6 on 2023-03-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=1024)),
                ('origem', models.CharField(max_length=256)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=64)),
                ('projeto', models.CharField(max_length=64)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'application_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('user_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstatisticasTabelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.TextField(blank=True, db_column='Tabela', null=True)),
                ('tamanho_da_tabela', models.TextField(blank=True, db_column='Tamanho da Tabela', null=True)),
                ('tamanho_do_indice', models.TextField(blank=True, db_column='Tamanho do Indice', null=True)),
                ('tamanho_total', models.TextField(blank=True, db_column='Tamanho Total', null=True)),
                ('data_da_coleta', models.TextField(blank=True, db_column='Data da Coleta', null=True)),
            ],
            options={
                'db_table': 'estatisticas_tabelas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpStaticStaticdevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField()),
                ('user_id', models.IntegerField()),
                ('throttling_failure_count', models.IntegerField()),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_static_staticdevice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpStaticStatictoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'otp_static_statictoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtpTotpTotpdevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField()),
                ('key', models.CharField(max_length=80)),
                ('step', models.SmallIntegerField()),
                ('t0', models.BigIntegerField()),
                ('digits', models.SmallIntegerField()),
                ('tolerance', models.SmallIntegerField()),
                ('drift', models.SmallIntegerField()),
                ('last_t', models.BigIntegerField()),
                ('user_id', models.IntegerField()),
                ('throttling_failure_count', models.IntegerField()),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_totp_totpdevice',
                'managed': False,
            },
        ),
    ]
